name: Build
on:
  push:
    branches: ["main", "dev"]
  pull_request:
    branches: ["main", "dev"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4
      - name: Build CLI
        run: cargo build -p mcvm_cli --release --verbose --locked
      - uses: actions/upload-artifact@v4
        name: Upload CLI artifact
        with:
          name: ${{ matrix.os }}
          path: target/release/mcvm*
