name: Docs
on:
  push:
    branches: ["main"]

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install Theme
        run: git submodule update --init --recursive
      - name: Install Zola
        uses: taiki-e/install-action@v2
        with:
          tool: zola@0.17.1
      - name: Build Docs
        run: cd docs && zola build --force
      - name: Debug
        run: pwd && ls docs/public
      - name: Upload docs artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/public
  deploy-docs:
    needs: build-docs

    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

